version: 2

project_name: chihuaudit

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/chihuaudit
    binary: chihuaudit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

upx:
  - enabled: true
    compress: best
    lzma: true
    brute: false

# Docker build is handled by separate docker.yml workflow
# dockers section removed to avoid conflicts

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    signature: '${artifact}.sig'
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: all
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: chihuaudit
  name_template: "V {{.Version}} Teacup"
  prerelease: auto
  draft: false
  header: |
    ## 📦 Download Instructions

    Choose the right binary for your system:

    | OS | Architecture | File | Use Case |
    |---|---|---|---|
    | 🐧 Linux | Intel/AMD 64-bit | `chihuaudit_{{.Tag}}_linux_amd64.tar.gz` | Most Linux servers & desktops |
    | 🐧 Linux | ARM 64-bit | `chihuaudit_{{.Tag}}_linux_arm64.tar.gz` | Raspberry Pi 4+, ARM servers |
    | 🍎 macOS | Intel | `chihuaudit_{{.Tag}}_darwin_amd64.tar.gz` | macOS Intel chips |
    | 🍎 macOS | Apple Silicon | `chihuaudit_{{.Tag}}_darwin_arm64.tar.gz` | M1/M2/M3/M4 Macs |

    ### Quick Install (Linux/macOS)

    ```bash
    # Download (replace with your architecture)
    wget https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/chihuaudit/releases/download/{{.Tag}}/chihuaudit_{{.Tag}}_linux_amd64.tar.gz

    # Extract
    tar xzf chihuaudit_{{.Tag}}_linux_amd64.tar.gz

    # Run
    ./chihuaudit --help

    # Optional: Move to PATH
    sudo mv chihuaudit /usr/local/bin/
    ```

    ### Verify Download (Optional)

    ```bash
    # Download checksums
    wget https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/chihuaudit/releases/download/{{.Tag}}/checksums.txt

    # Verify
    sha256sum -c checksums.txt --ignore-missing
    ```

    ---
