version: 2

project_name: mcp-watchdog

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/mcp-watchdog
    binary: mcp-watchdog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: girste
    name: mcp-cybersec-watchdog
  name_template: "{{.Tag}}"
  prerelease: auto
  draft: false
  header: |
    ## 📦 Download Instructions

    Choose the right binary for your system:

    | OS | Architecture | File | Use Case |
    |---|---|---|---|
    | 🐧 Linux | Intel/AMD 64-bit | `mcp-watchdog_{{.Tag}}_linux_amd64.tar.gz` | Most Linux servers & desktops |
    | 🐧 Linux | ARM 64-bit | `mcp-watchdog_{{.Tag}}_linux_arm64.tar.gz` | Raspberry Pi 4+, ARM servers |
    | 🍎 macOS | Intel | `mcp-watchdog_{{.Tag}}_darwin_amd64.tar.gz` | macOS Intel chips |
    | 🍎 macOS | Apple Silicon | `mcp-watchdog_{{.Tag}}_darwin_arm64.tar.gz` | M1/M2/M3/M4 Macs |

    ### Quick Install (Linux/macOS)

    ```bash
    # Download (replace with your architecture)
    wget https://github.com/girste/mcp-cybersec-watchdog/releases/download/{{.Tag}}/mcp-watchdog_{{.Tag}}_linux_amd64.tar.gz

    # Extract
    tar xzf mcp-watchdog_{{.Tag}}_linux_amd64.tar.gz

    # Run
    ./mcp-watchdog --help

    # Optional: Move to PATH
    sudo mv mcp-watchdog /usr/local/bin/
    ```

    ### Verify Download (Optional)

    ```bash
    # Download checksums
    wget https://github.com/girste/mcp-cybersec-watchdog/releases/download/{{.Tag}}/checksums.txt

    # Verify
    sha256sum -c checksums.txt --ignore-missing
    ```

    ---
