package cis

// Ubuntu2204Level1Controls returns all CIS Level 1 controls for Ubuntu 22.04 LTS
func Ubuntu2204Level1Controls(checker *Checker) []ControlDefinition {
	return []ControlDefinition{
		// Section 1: Initial Setup - Filesystem Configuration
		{
			Control: CISControl{
				ID:           "1.1.1.1",
				Title:        "Ensure cramfs kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install cramfs /bin/false' to /etc/modprobe.d/cramfs.conf and blacklist cramfs",
				AuditCommand: "modprobe -n -v cramfs | grep -E '(cramfs|install)'",
			},
			Check: checker.CheckModuleDisabled("cramfs"),
		},
		{
			Control: CISControl{
				ID:           "1.1.1.2",
				Title:        "Ensure freevxfs kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install freevxfs /bin/false' to /etc/modprobe.d/freevxfs.conf and blacklist freevxfs",
				AuditCommand: "modprobe -n -v freevxfs | grep -E '(freevxfs|install)'",
			},
			Check: checker.CheckModuleDisabled("freevxfs"),
		},
		{
			Control: CISControl{
				ID:           "1.1.1.3",
				Title:        "Ensure jffs2 kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install jffs2 /bin/false' to /etc/modprobe.d/jffs2.conf and blacklist jffs2",
				AuditCommand: "modprobe -n -v jffs2 | grep -E '(jffs2|install)'",
			},
			Check: checker.CheckModuleDisabled("jffs2"),
		},
		{
			Control: CISControl{
				ID:           "1.1.1.4",
				Title:        "Ensure hfs kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install hfs /bin/false' to /etc/modprobe.d/hfs.conf and blacklist hfs",
				AuditCommand: "modprobe -n -v hfs | grep -E '(hfs|install)'",
			},
			Check: checker.CheckModuleDisabled("hfs"),
		},
		{
			Control: CISControl{
				ID:           "1.1.1.5",
				Title:        "Ensure hfsplus kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install hfsplus /bin/false' to /etc/modprobe.d/hfsplus.conf and blacklist hfsplus",
				AuditCommand: "modprobe -n -v hfsplus | grep -E '(hfsplus|install)'",
			},
			Check: checker.CheckModuleDisabled("hfsplus"),
		},
		{
			Control: CISControl{
				ID:           "1.1.1.6",
				Title:        "Ensure squashfs kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install squashfs /bin/false' to /etc/modprobe.d/squashfs.conf and blacklist squashfs",
				AuditCommand: "modprobe -n -v squashfs | grep -E '(squashfs|install)'",
			},
			Check: checker.CheckModuleDisabled("squashfs"),
		},
		{
			Control: CISControl{
				ID:           "1.1.1.7",
				Title:        "Ensure udf kernel module is not available",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install udf /bin/false' to /etc/modprobe.d/udf.conf and blacklist udf",
				AuditCommand: "modprobe -n -v udf | grep -E '(udf|install)'",
			},
			Check: checker.CheckModuleDisabled("udf"),
		},
		{
			Control: CISControl{
				ID:           "1.1.2",
				Title:        "Ensure /tmp is a separate partition",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Configure /tmp as a separate partition or use systemd tmp.mount",
				AuditCommand: "findmnt -n /tmp",
			},
			Check: checker.CheckTmpPartition,
		},
		{
			Control: CISControl{
				ID:           "1.1.3",
				Title:        "Ensure nodev option set on /tmp partition",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add nodev option to /tmp mount in /etc/fstab or tmp.mount",
				AuditCommand: "findmnt -n /tmp | grep nodev",
			},
			Check: checker.CheckMountOption("/tmp", "nodev"),
		},
		{
			Control: CISControl{
				ID:           "1.1.4",
				Title:        "Ensure nosuid option set on /tmp partition",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add nosuid option to /tmp mount in /etc/fstab or tmp.mount",
				AuditCommand: "findmnt -n /tmp | grep nosuid",
			},
			Check: checker.CheckMountOption("/tmp", "nosuid"),
		},
		{
			Control: CISControl{
				ID:           "1.1.5",
				Title:        "Ensure noexec option set on /tmp partition",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Add noexec option to /tmp mount in /etc/fstab or tmp.mount",
				AuditCommand: "findmnt -n /tmp | grep noexec",
			},
			Check: checker.CheckMountOption("/tmp", "noexec"),
		},
		{
			Control: CISControl{
				ID:           "1.4.1",
				Title:        "Ensure bootloader password is set",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Set GRUB bootloader password using grub-mkpasswd-pbkdf2",
				AuditCommand: "grep '^set superusers' /boot/grub/grub.cfg",
			},
			Check: checker.CheckBootloaderPassword,
		},
		{
			Control: CISControl{
				ID:           "1.4.2",
				Title:        "Ensure permissions on bootloader config are configured",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /boot/grub/grub.cfg && chmod og-rwx /boot/grub/grub.cfg",
				AuditCommand: "stat /boot/grub/grub.cfg",
			},
			Check: checker.CheckBootloaderPermissions,
		},
		{
			Control: CISControl{
				ID:           "1.5.1",
				Title:        "Ensure address space layout randomization (ASLR) is enabled",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Set kernel.randomize_va_space = 2 in /etc/sysctl.conf",
				AuditCommand: "sysctl kernel.randomize_va_space",
			},
			Check: checker.CheckASLR,
		},
		{
			Control: CISControl{
				ID:           "1.5.2",
				Title:        "Ensure prelink is not installed",
				Section:      "Initial Setup",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: apt purge prelink",
				AuditCommand: "dpkg -s prelink 2>&1 | grep -E '(Status|not installed)'",
			},
			Check: checker.CheckPackageNotInstalled("prelink"),
		},

		// Section 3: Network Configuration
		{
			Control: CISControl{
				ID:           "3.1.1",
				Title:        "Ensure IPv6 is disabled (if not required)",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Add net.ipv6.conf.all.disable_ipv6 = 1 to /etc/sysctl.conf or add ipv6.disable=1 to GRUB",
				AuditCommand: "sysctl net.ipv6.conf.all.disable_ipv6",
			},
			Check: checker.CheckIPv6Disabled,
		},
		{
			Control: CISControl{
				ID:           "3.2.1",
				Title:        "Ensure packet redirect sending is disabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.conf.all.send_redirects = 0 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.conf.all.send_redirects",
			},
			Check: checker.CheckSysctl("net.ipv4.conf.all.send_redirects", "0"),
		},
		{
			Control: CISControl{
				ID:           "3.2.2",
				Title:        "Ensure IP forwarding is disabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.ip_forward = 0 in /etc/sysctl.conf (Note: Docker requires IP forwarding enabled)",
				AuditCommand: "sysctl net.ipv4.ip_forward",
			},
			Check: checker.CheckIPForwarding(),
		},
		{
			Control: CISControl{
				ID:           "3.3.1",
				Title:        "Ensure source routed packets are not accepted",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.conf.all.accept_source_route = 0 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.conf.all.accept_source_route",
			},
			Check: checker.CheckSysctl("net.ipv4.conf.all.accept_source_route", "0"),
		},
		{
			Control: CISControl{
				ID:           "3.3.2",
				Title:        "Ensure ICMP redirects are not accepted",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.conf.all.accept_redirects = 0 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.conf.all.accept_redirects",
			},
			Check: checker.CheckSysctl("net.ipv4.conf.all.accept_redirects", "0"),
		},
		{
			Control: CISControl{
				ID:           "3.3.3",
				Title:        "Ensure secure ICMP redirects are not accepted",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.conf.all.secure_redirects = 0 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.conf.all.secure_redirects",
			},
			Check: checker.CheckSysctl("net.ipv4.conf.all.secure_redirects", "0"),
		},
		{
			Control: CISControl{
				ID:           "3.3.4",
				Title:        "Ensure suspicious packets are logged",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.conf.all.log_martians = 1 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.conf.all.log_martians",
			},
			Check: checker.CheckSysctl("net.ipv4.conf.all.log_martians", "1"),
		},
		{
			Control: CISControl{
				ID:           "3.3.5",
				Title:        "Ensure broadcast ICMP requests are ignored",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.icmp_echo_ignore_broadcasts = 1 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.icmp_echo_ignore_broadcasts",
			},
			Check: checker.CheckSysctl("net.ipv4.icmp_echo_ignore_broadcasts", "1"),
		},
		{
			Control: CISControl{
				ID:           "3.3.6",
				Title:        "Ensure bogus ICMP responses are ignored",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.icmp_ignore_bogus_error_responses = 1 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.icmp_ignore_bogus_error_responses",
			},
			Check: checker.CheckSysctl("net.ipv4.icmp_ignore_bogus_error_responses", "1"),
		},
		{
			Control: CISControl{
				ID:           "3.3.7",
				Title:        "Ensure Reverse Path Filtering is enabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.conf.all.rp_filter = 1 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.conf.all.rp_filter",
			},
			Check: checker.CheckSysctl("net.ipv4.conf.all.rp_filter", "1"),
		},
		{
			Control: CISControl{
				ID:           "3.3.8",
				Title:        "Ensure TCP SYN Cookies is enabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv4.tcp_syncookies = 1 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv4.tcp_syncookies",
			},
			Check: checker.CheckSysctl("net.ipv4.tcp_syncookies", "1"),
		},
		{
			Control: CISControl{
				ID:           "3.3.9",
				Title:        "Ensure IPv6 router advertisements are not accepted",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Set net.ipv6.conf.all.accept_ra = 0 in /etc/sysctl.conf",
				AuditCommand: "sysctl net.ipv6.conf.all.accept_ra",
			},
			Check: checker.CheckSysctl("net.ipv6.conf.all.accept_ra", "0"),
		},
		{
			Control: CISControl{
				ID:           "3.4.1",
				Title:        "Ensure a firewall package is installed",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Install ufw: apt install ufw",
				AuditCommand: "dpkg -s ufw 2>&1 | grep Status",
			},
			Check: checker.CheckFirewallInstalled,
		},
		{
			Control: CISControl{
				ID:           "3.4.2",
				Title:        "Ensure firewall has default deny policy",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Configure firewall default deny: ufw default deny incoming",
				AuditCommand: "ufw status verbose | grep Default",
			},
			Check: checker.CheckFirewallDefaultDeny,
		},
		{
			Control: CISControl{
				ID:           "3.4.3",
				Title:        "Ensure firewall rules exist for all open ports",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Review open ports and ensure each has an explicit firewall rule",
				AuditCommand: "ss -tuln | grep LISTEN",
			},
			Check: checker.CheckFirewallRulesForOpenPorts,
		},
		{
			Control: CISControl{
				ID:           "3.5.1",
				Title:        "Ensure DCCP is disabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install dccp /bin/false' to /etc/modprobe.d/dccp.conf",
				AuditCommand: "modprobe -n -v dccp",
			},
			Check: checker.CheckModuleDisabled("dccp"),
		},
		{
			Control: CISControl{
				ID:           "3.5.2",
				Title:        "Ensure SCTP is disabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install sctp /bin/false' to /etc/modprobe.d/sctp.conf",
				AuditCommand: "modprobe -n -v sctp",
			},
			Check: checker.CheckModuleDisabled("sctp"),
		},
		{
			Control: CISControl{
				ID:           "3.5.3",
				Title:        "Ensure RDS is disabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install rds /bin/false' to /etc/modprobe.d/rds.conf",
				AuditCommand: "modprobe -n -v rds",
			},
			Check: checker.CheckModuleDisabled("rds"),
		},
		{
			Control: CISControl{
				ID:           "3.5.4",
				Title:        "Ensure TIPC is disabled",
				Section:      "Network Configuration",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'install tipc /bin/false' to /etc/modprobe.d/tipc.conf",
				AuditCommand: "modprobe -n -v tipc",
			},
			Check: checker.CheckModuleDisabled("tipc"),
		},

		// Section 4: Logging and Auditing
		{
			Control: CISControl{
				ID:           "4.1.1",
				Title:        "Ensure auditd is installed",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Install auditd: apt install auditd audispd-plugins",
				AuditCommand: "dpkg -s auditd",
			},
			Check: checker.CheckPackageInstalled("auditd"),
		},
		{
			Control: CISControl{
				ID:           "4.1.2",
				Title:        "Ensure auditd service is enabled and active",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Enable auditd: systemctl enable auditd && systemctl start auditd",
				AuditCommand: "systemctl is-enabled auditd && systemctl is-active auditd",
			},
			Check: checker.CheckServiceEnabled("auditd"),
		},
		{
			Control: CISControl{
				ID:           "4.2.1.1",
				Title:        "Ensure rsyslog is installed",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Install rsyslog: apt install rsyslog",
				AuditCommand: "dpkg -s rsyslog",
			},
			Check: checker.CheckPackageInstalled("rsyslog"),
		},
		{
			Control: CISControl{
				ID:           "4.2.1.2",
				Title:        "Ensure rsyslog service is enabled and active",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Enable rsyslog: systemctl enable rsyslog && systemctl start rsyslog",
				AuditCommand: "systemctl is-enabled rsyslog && systemctl is-active rsyslog",
			},
			Check: checker.CheckServiceEnabled("rsyslog"),
		},
		{
			Control: CISControl{
				ID:           "4.2.1.3",
				Title:        "Ensure rsyslog default file permissions are configured",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Add $FileCreateMode 0640 to /etc/rsyslog.conf or /etc/rsyslog.d/*.conf",
				AuditCommand: "grep ^\\$FileCreateMode /etc/rsyslog.conf /etc/rsyslog.d/*.conf",
			},
			Check: checker.CheckRsyslogFilePermissions,
		},
		{
			Control: CISControl{
				ID:           "4.2.2.1",
				Title:        "Ensure journald is configured to compress large log files",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Set Compress=yes in /etc/systemd/journald.conf",
				AuditCommand: "grep -E '^Compress' /etc/systemd/journald.conf",
			},
			Check: checker.CheckJournaldCompress,
		},
		{
			Control: CISControl{
				ID:           "4.2.2.2",
				Title:        "Ensure journald is configured to write logs to persistent storage",
				Section:      "Logging and Auditing",
				Level:        1,
				Scored:       true,
				Remediation:  "Set Storage=persistent in /etc/systemd/journald.conf",
				AuditCommand: "grep -E '^Storage' /etc/systemd/journald.conf",
			},
			Check: checker.CheckJournaldStorage,
		},

		// Section 5: Access, Authentication and Authorization
		{
			Control: CISControl{
				ID:           "5.1.1",
				Title:        "Ensure cron daemon is enabled and active",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Enable cron: systemctl enable cron && systemctl start cron",
				AuditCommand: "systemctl is-enabled cron && systemctl is-active cron",
			},
			Check: checker.CheckServiceEnabled("cron"),
		},
		{
			Control: CISControl{
				ID:           "5.1.2",
				Title:        "Ensure permissions on /etc/crontab are configured",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/crontab && chmod og-rwx /etc/crontab",
				AuditCommand: "stat /etc/crontab",
			},
			Check: checker.CheckFilePermissions("/etc/crontab", 0600, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "5.1.3",
				Title:        "Ensure permissions on /etc/cron.hourly are configured",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/cron.hourly && chmod og-rwx /etc/cron.hourly",
				AuditCommand: "stat /etc/cron.hourly",
			},
			Check: checker.CheckFilePermissions("/etc/cron.hourly", 0700, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "5.1.4",
				Title:        "Ensure permissions on /etc/cron.daily are configured",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/cron.daily && chmod og-rwx /etc/cron.daily",
				AuditCommand: "stat /etc/cron.daily",
			},
			Check: checker.CheckFilePermissions("/etc/cron.daily", 0700, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "5.1.5",
				Title:        "Ensure permissions on /etc/cron.weekly are configured",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/cron.weekly && chmod og-rwx /etc/cron.weekly",
				AuditCommand: "stat /etc/cron.weekly",
			},
			Check: checker.CheckFilePermissions("/etc/cron.weekly", 0700, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "5.1.6",
				Title:        "Ensure permissions on /etc/cron.monthly are configured",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/cron.monthly && chmod og-rwx /etc/cron.monthly",
				AuditCommand: "stat /etc/cron.monthly",
			},
			Check: checker.CheckFilePermissions("/etc/cron.monthly", 0700, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "5.2.1",
				Title:        "Ensure sudo is installed",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Install sudo: apt install sudo",
				AuditCommand: "dpkg -s sudo",
			},
			Check: checker.CheckPackageInstalled("sudo"),
		},
		{
			Control: CISControl{
				ID:           "5.2.2",
				Title:        "Ensure sudo commands use pty",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'Defaults use_pty' to /etc/sudoers",
				AuditCommand: "grep -Ei '^\\s*Defaults\\s+([^#]+,\\s*)?use_pty' /etc/sudoers /etc/sudoers.d/*",
			},
			Check: checker.CheckSudoUsePty,
		},
		{
			Control: CISControl{
				ID:           "5.2.3",
				Title:        "Ensure sudo log file exists",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Add 'Defaults logfile=\"/var/log/sudo.log\"' to /etc/sudoers",
				AuditCommand: "grep -Ei '^\\s*Defaults\\s+([^#]+,\\s*)?logfile=' /etc/sudoers /etc/sudoers.d/*",
			},
			Check: checker.CheckSudoLogFile,
		},
		{
			Control: CISControl{
				ID:           "5.3.1",
				Title:        "Ensure permissions on /etc/ssh/sshd_config are configured",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/ssh/sshd_config && chmod og-rwx /etc/ssh/sshd_config",
				AuditCommand: "stat /etc/ssh/sshd_config",
			},
			Check: checker.CheckFilePermissions("/etc/ssh/sshd_config", 0600, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "5.3.2",
				Title:        "Ensure SSH LogLevel is set to INFO or VERBOSE",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set LogLevel INFO or LogLevel VERBOSE in /etc/ssh/sshd_config",
				AuditCommand: "sshd -T | grep loglevel",
			},
			Check: checker.CheckSSHLogLevel,
		},
		{
			Control: CISControl{
				ID:           "5.3.3",
				Title:        "Ensure SSH X11 forwarding is disabled",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set X11Forwarding no in /etc/ssh/sshd_config",
				AuditCommand: "sshd -T | grep x11forwarding",
			},
			Check: checker.CheckSSHX11Forwarding,
		},
		{
			Control: CISControl{
				ID:           "5.3.4",
				Title:        "Ensure SSH MaxAuthTries is set to 4 or less",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set MaxAuthTries 4 in /etc/ssh/sshd_config",
				AuditCommand: "sshd -T | grep maxauthtries",
			},
			Check: checker.CheckSSHMaxAuthTries,
		},
		{
			Control: CISControl{
				ID:           "5.3.5",
				Title:        "Ensure SSH PermitRootLogin is disabled",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set PermitRootLogin no in /etc/ssh/sshd_config",
				AuditCommand: "sshd -T | grep permitrootlogin",
			},
			Check: checker.CheckSSHPermitRootLogin,
		},
		{
			Control: CISControl{
				ID:           "5.3.6",
				Title:        "Ensure SSH PermitEmptyPasswords is disabled",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set PermitEmptyPasswords no in /etc/ssh/sshd_config",
				AuditCommand: "sshd -T | grep permitemptypasswords",
			},
			Check: checker.CheckSSHPermitEmptyPasswords,
		},
		{
			Control: CISControl{
				ID:           "5.4.1",
				Title:        "Ensure password expiration is 365 days or less",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set PASS_MAX_DAYS 365 in /etc/login.defs",
				AuditCommand: "grep PASS_MAX_DAYS /etc/login.defs",
			},
			Check: checker.CheckPasswordMaxDays,
		},
		{
			Control: CISControl{
				ID:           "5.4.2",
				Title:        "Ensure minimum days between password changes is 1 or more",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set PASS_MIN_DAYS 1 in /etc/login.defs",
				AuditCommand: "grep PASS_MIN_DAYS /etc/login.defs",
			},
			Check: checker.CheckPasswordMinDays,
		},
		{
			Control: CISControl{
				ID:           "5.4.3",
				Title:        "Ensure password expiration warning days is 7 or more",
				Section:      "Access Control",
				Level:        1,
				Scored:       true,
				Remediation:  "Set PASS_WARN_AGE 7 in /etc/login.defs",
				AuditCommand: "grep PASS_WARN_AGE /etc/login.defs",
			},
			Check: checker.CheckPasswordWarnAge,
		},

		// Section 6: System Maintenance
		{
			Control: CISControl{
				ID:           "6.1.1",
				Title:        "Ensure permissions on /etc/passwd are configured",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/passwd && chmod 644 /etc/passwd",
				AuditCommand: "stat /etc/passwd",
			},
			Check: checker.CheckFilePermissions("/etc/passwd", 0644, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "6.1.2",
				Title:        "Ensure permissions on /etc/shadow are configured",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:shadow /etc/shadow && chmod 640 /etc/shadow",
				AuditCommand: "stat /etc/shadow",
			},
			Check: checker.CheckShadowPermissions,
		},
		{
			Control: CISControl{
				ID:           "6.1.3",
				Title:        "Ensure permissions on /etc/group are configured",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:root /etc/group && chmod 644 /etc/group",
				AuditCommand: "stat /etc/group",
			},
			Check: checker.CheckFilePermissions("/etc/group", 0644, 0, 0),
		},
		{
			Control: CISControl{
				ID:           "6.1.4",
				Title:        "Ensure permissions on /etc/gshadow are configured",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: chown root:shadow /etc/gshadow && chmod 640 /etc/gshadow",
				AuditCommand: "stat /etc/gshadow",
			},
			Check: checker.CheckGshadowPermissions,
		},
		{
			Control: CISControl{
				ID:           "6.2.1",
				Title:        "Ensure accounts in /etc/passwd use shadowed passwords",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Run: pwconv to convert to shadow passwords",
				AuditCommand: "awk -F: '($2 != \"x\") { print $1 }' /etc/passwd",
			},
			Check: checker.CheckShadowedPasswords,
		},
		{
			Control: CISControl{
				ID:           "6.2.2",
				Title:        "Ensure /etc/shadow password fields are not empty",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Set passwords for accounts or lock unused accounts",
				AuditCommand: "awk -F: '($2 == \"\") { print $1 }' /etc/shadow",
			},
			Check: checker.CheckNoEmptyPasswords,
		},
		{
			Control: CISControl{
				ID:           "6.2.3",
				Title:        "Ensure all groups in /etc/passwd exist in /etc/group",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Create missing groups or fix GID in /etc/passwd",
				AuditCommand: "for i in $(cut -s -d: -f4 /etc/passwd | sort -u); do grep -q -P \"^.*?:[^:]*:$i:\" /etc/group; [ $? -ne 0 ] && echo \"Group $i not in /etc/group\"; done",
			},
			Check: checker.CheckGroupsExist,
		},
		{
			Control: CISControl{
				ID:           "6.2.4",
				Title:        "Ensure no duplicate UIDs exist",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Fix duplicate UIDs in /etc/passwd",
				AuditCommand: "cut -d: -f3 /etc/passwd | sort | uniq -d",
			},
			Check: checker.CheckNoDuplicateUIDs,
		},
		{
			Control: CISControl{
				ID:           "6.2.5",
				Title:        "Ensure no duplicate GIDs exist",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Fix duplicate GIDs in /etc/group",
				AuditCommand: "cut -d: -f3 /etc/group | sort | uniq -d",
			},
			Check: checker.CheckNoDuplicateGIDs,
		},
		{
			Control: CISControl{
				ID:           "6.2.6",
				Title:        "Ensure root is the only UID 0 account",
				Section:      "System Maintenance",
				Level:        1,
				Scored:       true,
				Remediation:  "Remove or change UID for non-root accounts with UID 0",
				AuditCommand: "awk -F: '($3 == 0) { print $1 }' /etc/passwd",
			},
			Check: checker.CheckRootOnlyUID0,
		},
	}
}
